language: generic


sudo: required
services:
  - docker


before_install:
  - docker build -t nilanjan/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true nilanjan/react-app npm run test -- --coverage