version: '3'
services:
    web: 
        environment:
            - CHOKIDAR_USEPOLLINGF=true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "8080:3000"
        volumes:
            - /app/node_modules
            - .:/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]